-- Заполнение справочника пород собак и кошек
-- Источник: популярные породы в России

-- Породы собак (species_id = 1)
INSERT OR IGNORE INTO breeds (species_id, name, name_en) VALUES
-- Маленькие породы
(1, 'Йоркширский терьер', 'Yorkshire Terrier'),
(1, 'Чихуахуа', 'Chihuahua'),
(1, 'Той-терьер', 'Toy Terrier'),
(1, 'Померанский шпиц', 'Pomeranian'),
(1, 'Мопс', 'Pug'),
(1, 'Французский бульдог', 'French Bulldog'),
(1, 'Джек-рассел-терьер', 'Jack Russell Terrier'),
(1, 'Такса', 'Dachshund'),
(1, 'Пекинес', 'Pekingese'),
(1, 'Ши-тцу', 'Shih Tzu'),
(1, 'Бостон-терьер', 'Boston Terrier'),
(1, 'Вест-хайленд-уайт-терьер', 'West Highland White Terrier'),
(1, 'Цвергшнауцер', 'Miniature Schnauzer'),
(1, 'Бигль', 'Beagle'),
(1, 'Кавалер-кинг-чарльз-спаниель', 'Cavalier King Charles Spaniel'),

-- Средние породы
(1, 'Кокер-спаниель', 'Cocker Spaniel'),
(1, 'Английский кокер-спаниель', 'English Cocker Spaniel'),
(1, 'Бордер-колли', 'Border Collie'),
(1, 'Австралийская овчарка', 'Australian Shepherd'),
(1, 'Шелти', 'Shetland Sheepdog'),
(1, 'Вельш-корги пемброк', 'Pembroke Welsh Corgi'),
(1, 'Вельш-корги кардиган', 'Cardigan Welsh Corgi'),
(1, 'Бультерьер', 'Bull Terrier'),
(1, 'Стаффордширский бультерьер', 'Staffordshire Bull Terrier'),
(1, 'Американский стаффордширский терьер', 'American Staffordshire Terrier'),
(1, 'Шарпей', 'Shar Pei'),
(1, 'Чау-чау', 'Chow Chow'),
(1, 'Басенджи', 'Basenji'),
(1, 'Сиба-ину', 'Shiba Inu'),

-- Большие породы
(1, 'Лабрадор-ретривер', 'Labrador Retriever'),
(1, 'Золотистый ретривер', 'Golden Retriever'),
(1, 'Немецкая овчарка', 'German Shepherd'),
(1, 'Хаски', 'Siberian Husky'),
(1, 'Маламут', 'Alaskan Malamute'),
(1, 'Самоедская собака', 'Samoyed'),
(1, 'Акита-ину', 'Akita Inu'),
(1, 'Ротвейлер', 'Rottweiler'),
(1, 'Доберман', 'Doberman Pinscher'),
(1, 'Боксёр', 'Boxer'),
(1, 'Далматин', 'Dalmatian'),
(1, 'Английский бульдог', 'English Bulldog'),
(1, 'Американский бульдог', 'American Bulldog'),
(1, 'Кане-корсо', 'Cane Corso'),
(1, 'Бернский зенненхунд', 'Bernese Mountain Dog'),
(1, 'Сенбернар', 'Saint Bernard'),
(1, 'Ньюфаундленд', 'Newfoundland'),
(1, 'Московская сторожевая', 'Moscow Watchdog'),
(1, 'Кавказская овчарка', 'Caucasian Shepherd Dog'),
(1, 'Среднеазиатская овчарка (Алабай)', 'Central Asian Shepherd Dog'),
(1, 'Бельгийская овчарка', 'Belgian Shepherd'),
(1, 'Колли', 'Collie'),
(1, 'Английский сеттер', 'English Setter'),
(1, 'Ирландский сеттер', 'Irish Setter'),
(1, 'Веймаранер', 'Weimaraner'),
(1, 'Курцхаар', 'German Shorthaired Pointer'),
(1, 'Дратхаар', 'German Wirehaired Pointer'),
(1, 'Родезийский риджбек', 'Rhodesian Ridgeback'),
(1, 'Афганская борзая', 'Afghan Hound'),
(1, 'Русская псовая борзая', 'Borzoi'),
(1, 'Ирландский волкодав', 'Irish Wolfhound'),
(1, 'Английский мастиф', 'English Mastiff'),
(1, 'Бульмастиф', 'Bullmastiff'),
(1, 'Немецкий дог', 'Great Dane'),
(1, 'Леонбергер', 'Leonberger'),
(1, 'Тибетский мастиф', 'Tibetan Mastiff'),

-- Декоративные и редкие
(1, 'Пудель', 'Poodle'),
(1, 'Той-пудель', 'Toy Poodle'),
(1, 'Карликовый пудель', 'Miniature Poodle'),
(1, 'Мальтийская болонка', 'Maltese'),
(1, 'Бишон фризе', 'Bichon Frise'),
(1, 'Болонка', 'Bolognese'),
(1, 'Папильон', 'Papillon'),
(1, 'Китайская хохлатая', 'Chinese Crested Dog'),
(1, 'Басset-хаунд', 'Basset Hound'),
(1, 'Бладхаунд', 'Bloodhound'),
(1, 'Фокстерьер', 'Fox Terrier'),
(1, 'Эрдельтерьер', 'Airedale Terrier'),
(1, 'Скотч-терьер', 'Scottish Terrier'),
(1, 'Керн-терьер', 'Cairn Terrier'),
(1, 'Норвич-терьер', 'Norwich Terrier'),
(1, 'Норфолк-терьер', 'Norfolk Terrier');

-- Породы кошек (species_id = 2)
INSERT OR IGNORE INTO breeds (species_id, name, name_en) VALUES
-- Короткошёрстные
(2, 'Британская короткошёрстная', 'British Shorthair'),
(2, 'Шотландская вислоухая', 'Scottish Fold'),
(2, 'Шотландская прямоухая', 'Scottish Straight'),
(2, 'Русская голубая', 'Russian Blue'),
(2, 'Абиссинская', 'Abyssinian'),
(2, 'Бенгальская', 'Bengal'),
(2, 'Сиамская', 'Siamese'),
(2, 'Ориентальная', 'Oriental'),
(2, 'Бурманская', 'Burmese'),
(2, 'Тонкинская', 'Tonkinese'),
(2, 'Корниш-рекс', 'Cornish Rex'),
(2, 'Девон-рекс', 'Devon Rex'),
(2, 'Сфинкс', 'Sphynx'),
(2, 'Донской сфинкс', 'Donskoy'),
(2, 'Петерболд', 'Peterbald'),
(2, 'Бомбейская', 'Bombay'),
(2, 'Египетская мау', 'Egyptian Mau'),
(2, 'Американская короткошёрстная', 'American Shorthair'),
(2, 'Европейская короткошёрстная', 'European Shorthair'),
(2, 'Экзотическая короткошёрстная', 'Exotic Shorthair'),
(2, 'Манчкин', 'Munchkin'),
(2, 'Сингапурская', 'Singapura'),
(2, 'Бурмилла', 'Burmilla'),
(2, 'Оцикет', 'Ocicat'),
(2, 'Саванна', 'Savannah'),
(2, 'Тойгер', 'Toyger'),
(2, 'Сококе', 'Sokoke'),

-- Полудлинношёрстные
(2, 'Мейн-кун', 'Maine Coon'),
(2, 'Норвежская лесная', 'Norwegian Forest Cat'),
(2, 'Сибирская', 'Siberian'),
(2, 'Невская маскарадная', 'Neva Masquerade'),
(2, 'Рэгдолл', 'Ragdoll'),
(2, 'Бирманская', 'Birman'),
(2, 'Турецкая ангора', 'Turkish Angora'),
(2, 'Турецкий ван', 'Turkish Van'),
(2, 'Сомалийская', 'Somali'),
(2, 'Балинезийская', 'Balinese'),
(2, 'Яванская', 'Javanese'),
(2, 'Курильский бобтейл', 'Kurilian Bobtail'),
(2, 'Американский бобтейл', 'American Bobtail'),
(2, 'Японский бобтейл', 'Japanese Bobtail'),
(2, 'Пиксибоб', 'Pixiebob'),

-- Длинношёрстные
(2, 'Персидская', 'Persian'),
(2, 'Гималайская', 'Himalayan'),
(2, 'Британская длинношёрстная', 'British Longhair'),
(2, 'Селkirk-рекс', 'Selkirk Rex'),
(2, 'Лаперм', 'LaPerm'),
(2, 'Рагамаффин', 'Ragamuffin'),
(2, 'Шантильи-тиффани', 'Chantilly-Tiffany'),

-- Редкие и экзотические
(2, 'Као-мани', 'Khao Manee'),
(2, 'Корат', 'Korat'),
(2, 'Бурмилла', 'Burmilla'),
(2, 'Шартрез', 'Chartreux'),
(2, 'Нибелунг', 'Nebelung'),
(2, 'Гавана', 'Havana Brown'),
(2, 'Американский керл', 'American Curl'),
(2, 'Украинский левкой', 'Ukrainian Levkoy'),
(2, 'Минскин', 'Minskin'),
(2, 'Двэльф', 'Dwelf'),
(2, 'Бамбино', 'Bambino'),
(2, 'Наполеон', 'Napoleon'),
(2, 'Лайкой', 'Lykoi'),
(2, 'Серенгети', 'Serengeti'),
(2, 'Чаузи', 'Chausie'),
(2, 'Хайленд-фолд', 'Highland Fold'),
(2, 'Мэнкс', 'Manx'),
(2, 'Кимрик', 'Cymric');

-- Метисы и беспородные
INSERT OR IGNORE INTO breeds (species_id, name, name_en) VALUES
(1, 'Метис', 'Mixed Breed'),
(1, 'Беспородная', 'Mongrel'),
(2, 'Метис', 'Mixed Breed'),
(2, 'Беспородная', 'Domestic');
